# Generated by Django 6.0.3 on 2026-04-26 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='subject_code',
        ),
        migrations.AlterField(
            model_name='material',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colleges.college'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('NOTES', 'Notes'), ('ASSIGNMENT', 'Assignment / Teacher Suggestion'), ('PLACEMENT', 'Placement Notes')], default='NOTES', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='colleges.stream'),
        ),
    ]
