# Generated by Django 6.0.3 on 2026-04-27 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('materials', '0002_remove_material_subject_code_alter_material_college_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='college',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colleges.college'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='colleges.stream'),
            preserve_default=False,
        ),
    ]
