# Generated by Django 6.0.3 on 2026-03-10 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')])),
                ('year', models.IntegerField()),
                ('subject_name', models.CharField(max_length=150)),
                ('exam_type', models.CharField(choices=[('INTERNAL', 'Internal / CA'), ('SEMESTER', 'Semester (End-Sem)'), ('PRACTICAL', 'Practical Exam')], max_length=20)),
                ('pdf_file', models.FileField(upload_to='papers/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.stream')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
