# Generated by Django 6.0.3 on 2026-03-12 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('university', models.CharField(choices=[('MAKAUT', 'MAKAUT (formerly WBUT)'), ('JU', 'Jadavpur University'), ('CU', 'Calcutta University'), ('AUTONOMOUS', 'Autonomous Institution')], max_length=20)),
                ('logo', models.ImageField(blank=True, upload_to='college_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='colleges.college')),
            ],
        ),
    ]
