# Generated by Django 6.0.3 on 2026-09-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='stream',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='college',
            name='slug',
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together={('college', 'name')},
        ),
    ]
